ClienteSIGREI/Controllers/BandejaSolicitudController.cs
using ClienteSIGREI.Util;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Osiptel.SIGREI.BE;
using Osiptel.SIGREI.BL;
using PPBMS.GLOBALTPA.ClienteWeb.Filter;
using System;
using System.Collections.Generic;

namespace ClienteSIGREI.Controllers
{
    [FilterUsuario]
    public class BandejaSolicitudController : Controller
    {
        public IActionResult Index()
        {

            BL_EMPRESA ObjLogica = new BL_EMPRESA();
            List<BE_EMPRESA> lista = ObjLogica.Listar(0);

            ViewBag.Lista_EmpresaEO = lista;

            List<EstadoBE> listaEstado = new List<EstadoBE>();
            EstadoBE objEstado = new EstadoBE();
            objEstado.IDESTADO = "1";
            objEstado.ESTADO = "Registrado";

            listaEstado.Add(objEstado);


            objEstado = new EstadoBE();
            objEstado.IDESTADO = "4";
            objEstado.ESTADO = "Atendido";
            listaEstado.Add(objEstado);

            ViewBag.Lista_Estado = listaEstado;

            BlParametro ObjLogicaP = new BlParametro();
            List<BE_PARAMETRO> listaP = ObjLogicaP.ListarValores(UTConstantes.APLICACION, UTConstantes.APLICACION_TABLA.TIPOMOTIVOVENCIMIENTO, UTConstantes.APLICACION_COLUMNA.IDTIPOMOTIVOVENCIMIENTO);
            ViewBag.Lista_Vencimiento = listaP;

            return View();
        }

        [HttpPost]
        public ActionResult BuscarSolicitudes(IFormCollection formulario)
        {

            List<BE_REQUERIMIENTO_EO> listaBE_REQUERIMIENTO = new List<BE_REQUERIMIENTO_EO>();
            BE_REQUERIMIENTO_EO objParametro = new BE_REQUERIMIENTO_EO();
            BL_REQUERIMIENTO_EO objLogica = new BL_REQUERIMIENTO_EO();

            objParametro = obtenerCriterios(formulario);

            listaBE_REQUERIMIENTO = objLogica.ListaSolicitudEO(objParametro);

            return PartialView("_DetalleSolicitud", listaBE_REQUERIMIENTO);
        }

        [HttpPost]
        public ActionResult LimpiarCriteriosBandeja(IFormCollection formulario)
        {
            List<BE_REQUERIMIENTO_EO> listaBE_REQUERIMIENTO = new List<BE_REQUERIMIENTO_EO>();

            return PartialView("_DetalleSolicitud", listaBE_REQUERIMIENTO);
        }


        public BE_REQUERIMIENTO_EO obtenerCriterios(IFormCollection formulario)
        {
            BE_REQUERIMIENTO_EO objResultado = new BE_REQUERIMIENTO_EO();
            objResultado.idEmpresaEO = formulario["ddlEmpresaOperadora"].ToString() == null || formulario["ddlEmpresaOperadora"].ToString() == "" ? 0 : Convert.ToInt32(formulario["ddlEmpresaOperadora"].ToString());
            objResultado.fechaInicio = formulario["txtFechaInicio"].ToString();
            objResultado.fechaFin = formulario["txtFechaFin"].ToString();
            objResultado.nroImei = formulario["txtNroImei"].ToString();
            objResultado.idEstado = formulario["ddlEstado"].ToString() == null || formulario["ddlEstado"].ToString() == "" ? 0 : Convert.ToInt32(formulario["ddlEstado"].ToString());
            return objResultado;
        }




        [HttpPost]
        public ActionResult CargaInicial(IFormCollection formulario)
        {

            List<BE_REQUERIMIENTO_EO> listaBE_REQUERIMIENTO = new List<BE_REQUERIMIENTO_EO>();
            return PartialView("_DetalleSolicitud", listaBE_REQUERIMIENTO);
        }

        [HttpPost]
        public ActionResult AmpliarVencimientoPlazo(IFormCollection formulario)
        {
            Int64 idResultado = 0;
            KeyValuePair<string, string> result = new KeyValuePair<string, string>();
            try
            {


                BE_REQUERIMIENTO_EO objEntidad = new BE_REQUERIMIENTO_EO();
                BL_REQUERIMIENTO_EO objLogica = new BL_REQUERIMIENTO_EO();
                objEntidad.idRequerimientoEO = Convert.ToInt64(formulario["ihrequerimientoeo"]);
                objEntidad.idTipoMotivoVencimiento = formulario["ddlMotivo"] == "" ? 0 : Convert.ToInt32(formulario["ddlMotivo"].ToString());
                objEntidad.fechaPlazo = formulario["txtFechaVencimiento"].ToString();
                objEntidad.usuMod = HttpContext.Session.GetString("IdUsuario");

                idResultado = objLogica.ActualizarVencimientoEO(objEntidad);
                if (idResultado > 0)
                {
                    HttpContext.Session.SetString("IrTabCargarInformacion", "1");
                    result = new KeyValuePair<string, string>("1", "¡Se ha ampliado la fecha de vencimiento  correctamente!");
                }
                else
                {
                    result = new KeyValuePair<string, string>("0", "Error al ampliar la fecha de vencimiento");
                }                
                return Json(result);
            }
            catch (Exception ex)
            {
                LogError.RegistrarErrorMetodo(ex, "AmpliarVencimientoPlazo");
                result = new KeyValuePair<string, string>("0", "Error al ampliar la fecha de vencimiento");
                
                return Json(result);
            }
        }

    }
}

ClienteSIGREI/Controllers/CargaInformacionController.cs
using ClienteSIGREI.Util;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using OfficeOpenXml;
using Osiptel.SIGREI.BE;
using Osiptel.SIGREI.BL;
using PPBMS.GLOBALTPA.ClienteWeb.Filter;
using System;
using System.Collections.Generic;
using System.IO;

namespace ClienteSIGREI.Controllers
{
    [FilterUsuario]
    public class CargaInformacionController : Controller
    {

        private readonly IConfiguration configuration;
        private readonly IHostingEnvironment hosting;
        public CargaInformacionController(IConfiguration config, IHostingEnvironment host)
        {
            this.configuration = config;
            this.hosting = host;
        }

        public IActionResult Index()
        {
            List<EstadoBE> listaEstado = new List<EstadoBE>();
            EstadoBE objEstado = new EstadoBE();
            objEstado.IDESTADO = "1";
            objEstado.ESTADO = "Registrado";
            listaEstado.Add(objEstado);

            objEstado = new EstadoBE();
            objEstado.IDESTADO = "4";
            objEstado.ESTADO = "Atendido";
            listaEstado.Add(objEstado);

            ViewBag.Lista_Estado = listaEstado;

            return View();
        }

        public ActionResult RecargarPaginaCarga()
        {

            return RedirectToAction("Index", "SistemaDocumentario");
        }

        [HttpPost]
        public ActionResult CargaInicial(IFormCollection formulario)
        {
            List<BE_REQUERIMIENTO_EO> listaBE_REQUERIMIENTO = new List<BE_REQUERIMIENTO_EO>();
            BE_REQUERIMIENTO_EO objParametro = obtenerCriterios(formulario);
            BL_REQUERIMIENTO_EO objLogica = new BL_REQUERIMIENTO_EO();

            objParametro.idEmpresaEO = Int64.Parse(HttpContext.Session.GetString("cod_Empresa"));
            listaBE_REQUERIMIENTO = objLogica.ListaSolicitudEO(objParametro);
            return PartialView("_DetalleCargaInformacion", listaBE_REQUERIMIENTO);
        }

        [HttpPost]
        public ActionResult BucarSolicitudes(IFormCollection formulario)
        {
            List<BE_REQUERIMIENTO_EO> listaBE_REQUERIMIENTO = new List<BE_REQUERIMIENTO_EO>();
            BE_REQUERIMIENTO_EO objParametro = obtenerCriterios(formulario);
            BL_REQUERIMIENTO_EO objLogica = new BL_REQUERIMIENTO_EO();

            objParametro.idEmpresaEO = Int64.Parse(HttpContext.Session.GetString("cod_Empresa"));
            listaBE_REQUERIMIENTO = objLogica.ListaSolicitudEO(objParametro);
            return PartialView("_DetalleCargaInformacion", listaBE_REQUERIMIENTO);
        }

        [HttpPost]
        public ActionResult LimpiarCriteriosBandeja(IFormCollection formulario)
        {
            List<BE_REQUERIMIENTO_EO> listaBE_REQUERIMIENTO = new List<BE_REQUERIMIENTO_EO>();

            return PartialView("_DetalleCargaInformacion", listaBE_REQUERIMIENTO);
        }


        [HttpPost]
        public ActionResult AtenderRequerimientoEO(IFormCollection formulario)
        {
            var ID = formulario["ihrequerimientoeo"];

            BE_REQUERIMIENTO_EO objBE_REQUERIMIENTOEO = new BE_REQUERIMIENTO_EO();
            BL_REQUERIMIENTO_EO objLogicaRequerimientoEO = new BL_REQUERIMIENTO_EO();
            Int64 idRetorno = 0;
            try
            {
                objBE_REQUERIMIENTOEO.idRequerimientoEO = Int64.Parse(ID);
                objBE_REQUERIMIENTOEO.usuMod = HttpContext.Session.GetString("IdUsuario");

                idRetorno = objLogicaRequerimientoEO.AtenderEO(objBE_REQUERIMIENTOEO);

                KeyValuePair<string, string> result = new KeyValuePair<string, string>();
                if (idRetorno > 0)
                {
                    result = new KeyValuePair<string, string>("1", "¡Se atendió correctamente el requerimiento de información!");
                }
                else
                {
                    result = new KeyValuePair<string, string>("0", "Error al intentar atender el requerimiento de información");
                }
                return Json(result);
            }
            catch (Exception)
            {
                KeyValuePair<string, string> result = new KeyValuePair<string, string>("0", "Error al intentar atender el requerimiento de información");
                return Json(result);
            }
        }


        [HttpPost]
        public ActionResult ConsultarIMEIPendientes(IFormCollection formulario)
        {
            KeyValuePair<string, string> result = new KeyValuePair<string, string>();
            var ID = formulario["ihrequerimientoeo"];

            BE_REQUERIMIENTO_EO objBE_REQUERIMIENTOEO = new BE_REQUERIMIENTO_EO();
            BL_REQUERIMIENTO_EO objLogica = new BL_REQUERIMIENTO_EO();
            try
            {
                objBE_REQUERIMIENTOEO.idRequerimientoEO = Int64.Parse(ID);

                objBE_REQUERIMIENTOEO = objLogica.ConsultaSolicitudEO(objBE_REQUERIMIENTOEO);


                if (objBE_REQUERIMIENTOEO.cantidadPorAtender > UTConstantes.VALOR_CERO)
                {
                    result = new KeyValuePair<string, string>("2", "¡No se puede atender el Requerimiento porque tiene IMEIs por atender!");
                }
                else
                {
                    result = new KeyValuePair<string, string>("1", "¡Se prosigue a atender!");
                }
                return Json(result);
            }
            catch (Exception)
            {
                result = new KeyValuePair<string, string>("0", "Error al intentar atender la solicitud de la empresa operadora");

                return Json(result);
            }
        }


        public FileResult DescargarDocumentoIMEI(IFormCollection formulario)
        {
            BL_REQUERIMIENTO_EO objLogica = new BL_REQUERIMIENTO_EO();
            BE_REQUERIMIENTO_IMEI_EO objBE_REQUERIMIENTO_IMEI = new BE_REQUERIMIENTO_IMEI_EO();

            objBE_REQUERIMIENTO_IMEI.idRequerimientoEO = Int64.Parse(formulario["ihrequerimientoeoDes"].ToString());

            byte[] FileExcel = null;
            ExportExcel objExportExcel = new ExportExcel();
            FileExcel = objExportExcel.generarIMEI_EO(objLogica.ListaIMEI_EO(objBE_REQUERIMIENTO_IMEI), "IMEI");

            return File(FileExcel, System.Net.Mime.MediaTypeNames.Application.Octet, formulario["ihrequerimientoeoDes"].ToString() + "_IMEI_EO.xlsx");
        }



        [HttpPost]
        public ActionResult ConsultaRequerimientoSolicitud(IFormCollection formulario)
        {
            BE_REQUERIMIENTO_EO objRequerimientoEO = new BE_REQUERIMIENTO_EO();
            BE_REQUERIMIENTO_IMEI_EO objRequerimientoImeiEo = new BE_REQUERIMIENTO_IMEI_EO();

            try
            {
                BL_REQUERIMIENTO_EO objLogicaRequerimiento = new BL_REQUERIMIENTO_EO();


                Int64 idRequerimientoEO = Int64.Parse(formulario["ihrequerimientoeo"].ToString());
                objRequerimientoEO.idRequerimientoEO = Convert.ToInt64(idRequerimientoEO);
                objRequerimientoEO = objLogicaRequerimiento.ConsultaSolicitudEO(objRequerimientoEO);

                objRequerimientoImeiEo.idRequerimientoEO = Convert.ToInt64(idRequerimientoEO);

                objRequerimientoEO.listaRequerimientoImeiEO = objLogicaRequerimiento.ListaIMEI_EO(objRequerimientoImeiEo);

            }
            catch (Exception)
            {
                objRequerimientoEO = new BE_REQUERIMIENTO_EO();
                objRequerimientoEO.listaRequerimientoImeiEO = new List<BE_REQUERIMIENTO_IMEI_EO>();

            }
            return PartialView("_PartialConsultaSolicitud", objRequerimientoEO);
        }


        [HttpPost]
        public ActionResult AbrirCargaInfoSolicitud(IFormCollection formulario)
        {
            BE_REQUERIMIENTO_EO objRequerimientoEO = new BE_REQUERIMIENTO_EO();
            BE_REQUERIMIENTO_IMEI_EO objRequerimientoImeiEo = new BE_REQUERIMIENTO_IMEI_EO();

            try
            {
                BL_REQUERIMIENTO_EO objLogicaRequerimiento = new BL_REQUERIMIENTO_EO();


                Int64 idRequerimientoEO = Int64.Parse(formulario["ihrequerimientoeo"].ToString());
                objRequerimientoEO.idRequerimientoEO = Convert.ToInt64(idRequerimientoEO);
                objRequerimientoEO = objLogicaRequerimiento.ConsultaSolicitudEO(objRequerimientoEO);


                var irTab = HttpContext.Session.GetString("IrTabCargarInformacion");

                if (irTab == null)
                {
                    irTab = "0";
                }
                else if (irTab == "1")
                {
                    HttpContext.Session.SetString("IrTabCargarInformacion", "0");
                }
                else
                {
                }

                ViewBag.IrTabPorAtender = irTab;

            }
            catch (Exception)
            {
                objRequerimientoEO = new BE_REQUERIMIENTO_EO();
                objRequerimientoEO.listaRequerimientoImeiEO = new List<BE_REQUERIMIENTO_IMEI_EO>();

            }
            return PartialView("_PartialCargaInformacion", objRequerimientoEO);
        }

        [HttpPost]
        public ActionResult verTabsAtendidas(IFormCollection formulario)
        {
            List<BE_REQUERIMIENTO_IMEI_EO> listaResultado = new List<BE_REQUERIMIENTO_IMEI_EO>();

            var listaResultadoJSON = JsonConvert.SerializeObject(listaResultado);
            HttpContext.Session.SetString("ListaImeiPorAtender", listaResultadoJSON);
            try
            {
                BL_REQUERIMIENTO_EO objLogicaRequerimiento = new BL_REQUERIMIENTO_EO();
                BE_REQUERIMIENTO_IMEI_EO objRequerimientoImeiEo = new BE_REQUERIMIENTO_IMEI_EO();
                Int64 idRequerimientoEO = Int64.Parse(formulario["ihrequerimientoeo"].ToString());
                objRequerimientoImeiEo.idRequerimientoEO = Convert.ToInt64(idRequerimientoEO);

ClienteSIGREI/Views/BandejaSolicitud/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "_Layout";
}
<form method="post" id="frmDescargarImei" enctype="multipart/form-data" asp-controller="CargaInformacion" asp-action="DescargarDocumentoIMEI">
    <input type="hidden" id="ihrequerimientoeoDes" name="ihrequerimientoeoDes" />
</form>
<form method="post" id="frmBandejaSolicitud" enctype="multipart/form-data">
    <input type="hidden" id="ihrequerimientoeo" name="ihrequerimientoeo" />
    <input type="hidden" name="ihidimeiDevolver" id="ihidimeiDevolver" value="" />
    <div class="container contenedor-bandeja">
        <div class="row">
            <div class="col-md-12">
                <div class="content-header cabecera-formulario">
                    <h3 style="color: #ffffff">Bandeja de Requerimientos EO</h3>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                <div class="etiqueta">
                    Empresa Operadora
                </div>
            </div>
            <div class="col-md-2">
                @Html.DropDownList("ddlEmpresaOperadora", new SelectList(ViewBag.Lista_EmpresaEO, "idEmpresa", "empresaOperadora"), "Todos", new { title = "Empresa Operadora", @class = "input-content ", @style = "width: 180px;" })
            </div>
            <div class="col-md-2">
                <div class="etiqueta">
                    Nro IMEI
                </div>
            </div>

            <div class="col-md-2">
                @Html.TextBox("txtNroImei", "", new { @class = "input-content", @maxlength = "20" , @onkeypress = "return soloNumeros(event)" })
            </div>

            <div class="col-md-2">
                <div class="etiqueta">
                    Estado
                </div>
            </div>
            <div class="col-md-2">
                @Html.DropDownList("ddlEstado", new SelectList(ViewBag.Lista_Estado, "IDESTADO", "ESTADO"), "Todos", new { title = "Estado", @class = "input-content " })
            </div>
        </div>

        <div class="row">
            <div class="col-md-2">
                <label class="etiqueta">
                    Fecha de Inicio:
                </label>
            </div>
            <div class="col-md-2">
                @Html.TextBox("txtFechaInicio", "", new { @class = "input-content fa fa-calendar", @maxlength = "20", @style = "width: 100px;" })
                @*<i class="fa fa-calendar" aria-hidden="true"></i>*@
            </div>
            <div class="col-md-2">
                <label class="etiqueta">
                    Hasta:
                </label>
            </div>
            <div class="col-md-2">
                @Html.TextBox("txtFechaFin", "", new { @class = "input-content", @maxlength = "20", @style = "width: 100px;" })
            </div>
            <div class="col-md-4">
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
            </div>
            <div class="col-md-4 text-right">
                <button type="button" id="btnLimpiarBandeja" class="btn class-button-bandeja">
                    Limpiar
                </button>
                <button type="button" id="btnBuscarSolicitudes" class="btn class-button-bandeja">
                    Buscar
                </button>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="" id="divSolicitudes">

                </div>
            </div>
        </div>
    </div>


    <div class="modal fade bd-example-modal-lg" id="modalConsultaSolicitud" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lx" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="content-header cabecera-formulario">
                        <h3 style="color: #ffffff">Consulta de información de IMEIs Requeridos</h3>
                    </div>
                    <button type="button" class="close-modal" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="" id="divConsultaImei">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-cancelar" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>


    <div class="modal fade bd-example-modal-lg" id="modalApliacion" tabindex="-2" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <input type="hidden" id="ihidImeiEO" name="ihidImeiEO" />
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="content-header cabecera-formulario">
                        <h3 style="color: #ffffff">Cambiar Fecha de Vencimiento</h3>
                    </div>
                    <button type="button" class="close-modal cerrar-modal-descarte" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="etiqueta">
                                Fecha de Envío a EO:
                            </div>
                        </div>
                        <div class="col-md-8">
                            <label id="lblFechaEnviadaEO" name="lblFechaEnviadaEO"></label>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="etiqueta">
                                Motivo
                            </div>
                        </div>
                        <div class="col-md-8">
                            @Html.DropDownList("ddlMotivo", new SelectList(ViewBag.Lista_Vencimiento, "valor", "descripcion"), "Seleccione", new { title = "Estado", @class = "input-content " })
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="etiqueta">
                                Fecha de Vencimiento:
                            </div>
                        </div>
                        <div class="col-md-8">
                            @Html.TextBox("txtFechaVencimiento", "", new { @class = "input-content", @maxlength = "20", @style = "width: 100px;" })
                        </div>
                    </div>
                  
                    <div class="modal-footer">
                        <button type="button" id="btnRenovarVencimiento" class="btn class-button-bandeja">Grabar</button>
                        <button type="button" id="btnCancelarDescarte" data-dismiss="modal" class="btn cerrar-modal-descarte btn-cancelar">Cancelar</button>
                    </div>
                </div>

            </div>
        </div>
    </div>

</form>

<script src="~/js/appjs/bandejaSolicitud/jsIndex.js"></script>

ClienteSIGREI/Views/BandejaSolicitud/_DetalleSolicitud.cshtml
@model List<Osiptel.SIGREI.BE.BE_REQUERIMIENTO_EO>;
@{    
    Layout = "";
}
<div class="tabla-content-result">
    <input type="hidden" id="hdreqeele" name="hdreqeele" />
    <table id="dtResultSolicitud" class="tabla-osiptel" style="width: 100%">
        <caption style="display: none">TablaDetalle</caption>
        <thead>
            <tr>

                <th scope="col">Nro</th>
                <th scope="col">Empresa Operadora</th>
                <th scope="col">Fecha Envío a EO</th>
                <th scope="col">Fecha Vencimiento</th>
                <th scope="col">Fecha Atención</th>
                <th scope="col">Cantidad IMEI Enviado </th>
                <th scope="col">Cantidad IMEI Por Atender</th>
                <th scope="col">Cantidad IMEI Atendido</th>
                <th scope="col">Estado</th>
                <th scope="col">Opciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">@item.nroItem</td>
                    <td class="text-left">@item.empresaOperadora</td>
                    <td class="text-center">@item.fecRegistro</td>
                    <td class="text-center">@item.fechaPlazo</td>
                    <td class="text-center">@item.fechaAtendido</td>
                    <td class="text-center">@item.cantidadRegistrado</td>
                    <td class="text-center">@item.cantidadPorAtender</td>
                    <td class="text-center">@item.cantidadAtendido</td>
                    <td class="text-center">@item.descEstado</td>
                    <td class="text-center">
                        <a href="#" onclick="fn_verConsultar(@item.idRequerimientoEO)" class="fa fa-eye fa-lg" title="Consultar"></a>
                        <a href="#" onclick="fn_CambiarFechaVencimiento(@item.idRequerimientoEO,'@item.fechaPlazo')" class="fa fa-exchange fa-lg" title="Cambiar Fecha de Vencimiento"></a>
                        <a href="#" onclick="fn_Descargar(@item.idRequerimientoEO)" class="fa fa-download fa-lg" title="Descargar IMEIs"></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<script src="~/js/appjs/bandejaSolicitud/jsDetalleIndex.js"></script>